modLoader = 'lowcodefml'
showAsResourcePack = false
loaderVersion="[47,)"
license="All rights reserved"

[[mods]]
modId="viggos_powers"
displayName="Viggos Powers"
version="1.0.0"
logoFile = "logo.png"
logoBlur = false
description='''
Cool powers
'''

[[dependencies.viggos_powers]]
modId = "palladium"
mandatory = true
versionRange = ""
ordering = "NONE"
side = "BOTH"
